package com.xpecya.responseStruct;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CashFlowResponse {

    private String ts_code;
    private String ann_date;
    private String f_ann_date;
    private String end_date;
    private String comp_type;
    private String report_type;
    private Float net_profit;
    private Float finan_exp;
    private Float c_fr_sale_sg;
    private Float recp_tax_rends;
    private Float n_depos_incr_fi;
    private Float n_incr_loans_cb;
    private Float n_inc_borr_oth_fi;
    private Float prem_fr_orig_contr;
    private Float n_incr_insured_dep;
    private Float n_reinsur_prem;
    private Float n_incr_disp_tfa;
    private Float ifc_cash_incr;
    private Float n_incr_disp_faas;
    private Float n_incr_loans_oth_bank;
    private Float n_cap_incr_repur;
    private Float c_fr_oth_operate_a;
    private Float c_inf_fr_operate_a;
    private Float c_paid_goods_s;
    private Float c_paid_to_for_empl;
    private Float c_paid_for_taxes;
    private Float n_incr_clt_loan_adv;
    private Float n_incr_dep_cbob;
    private Float c_pay_claims_orig_inco;
    private Float pay_handling_chrg;
    private Float pay_comm_insur_plcy;
    private Float oth_cash_pay_oper_act;
    private Float st_cash_out_act;
    private Float n_cashflow_act;
    private Float oth_recp_ral_inv_act;
    private Float c_disp_withdrwl_invest;
    private Float c_recp_return_invest;
    private Float n_recp_disp_fiolta;
    private Float n_recp_disp_sobu;
    private Float stot_inflows_inv_act;
    private Float c_pay_acq_const_fiolta;
    private Float c_paid_invest;
    private Float n_disp_subs_oth_biz;
    private Float oth_pay_ral_inv_act;
    private Float n_incr_pledge_loan;
    private Float stot_out_inv_act;
    private Float n_cashflow_inv_act;
    private Float c_recp_borrow;
    private Float proc_issue_bonds;
    private Float oth_cash_recp_ral_fnc_act;
    private Float stot_cash_in_fnc_act;
    private Float free_cashflow;
    private Float c_prepay_amt_borr;
    private Float c_pay_dist_dpcp_int_exp;
    private Float incl_dvd_profit_paid_sc_ms;
    private Float oth_cashpay_ral_fnc_act;
    private Float stot_cashout_fnc_act;
    private Float n_cash_flows_fnc_act;
    private Float eff_fx_flu_cash;
    private Float n_incr_cash_cash_equ;
    private Float c_cash_equ_beg_period;
    private Float c_cash_equ_end_period;
    private Float c_recp_cap_contrib;
    private Float incl_cash_rec_saims;
    private Float uncon_invest_loss;
    private Float prov_depr_assets;
    private Float depr_fa_coga_dpba;
    private Float amort_intang_assets;
    private Float lt_amort_deferred_exp;
    private Float decr_deferred_exp;
    private Float incr_acc_exp;
    private Float loss_disp_fiolta;
    private Float loss_scr_fa;
    private Float loss_fv_chg;
    private Float invest_loss;
    private Float decr_def_inc_tax_assets;
    private Float incr_def_inc_tax_liab;
    private Float decr_inventories;
    private Float decr_oper_payable;
    private Float incr_oper_payable;
    private Float others;
    private Float im_net_cashflow_oper_act;
    private Float conv_debt_into_cap;
    private Float conv_copbonds_due_within_1y;
    private Float fa_fnc_leases;
    private Float end_bal_cash;
    private Float beg_bal_cash;
    private Float end_bal_cash_equ;
    private Float beg_bal_cash_equ;
    private Float im_n_incr_cash_equ;
    private String update_flag;

}
